version: '3.3'
services:
  e2e-app:
    build:
      context: .
      dockerfile: Dockerfile-e2e-app
    container_name: e2e-app
    hostname: e2e-app
#    ports:
#      - "5105:5105"
    environment:
      - SPP_DISABLE_TLS=true
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5455:5455"
    environment:
      - SPP_DISABLE_TLS=true
      - SPP_DISABLE_JWT=true
  skywalking-oap:
    build:
      context: .
      dockerfile: Dockerfile-skywalking-oap
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
#      - "5106:5106"
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_DISABLE_TLS=true
#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5106
