name: Build processor

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.svg'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.svg'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Export Properties
      id: properties
      shell: bash
      run: |
        PROPERTIES="$(./gradlew properties --console=plain -q)"
        VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
        echo "::set-output name=version::$VERSION"
        echo "SPP_INSTRUMENT_PROCESSOR_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew build

    - name: Remove Old Release Drafts
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
          | tr '\r\n' ' ' \
          | jq '.[] | select(.draft == true) | .id' \
          | xargs -I '{}' \
        curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}

    - name: Create Release Draft
      if: github.ref == 'refs/heads/master'
      id: createDraft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.SPP_INSTRUMENT_PROCESSOR_VERSION }}
        release_name: v${{ env.SPP_INSTRUMENT_PROCESSOR_VERSION }}
        draft: true

    - name: Upload spp-processor-instrument asset
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createDraft.outputs.upload_url }}
        asset_path: ./build/libs/spp-processor-instrument-${{ env.SPP_INSTRUMENT_PROCESSOR_VERSION }}.jar
        asset_name: spp-processor-instrument-${{ env.SPP_INSTRUMENT_PROCESSOR_VERSION }}.jar
        asset_content_type: application/java-archive
